create database PETS;
use PETS;

CREATE TABLE PERSON (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    AGE INTEGER,
    PRIMARY KEY (ID)
);

INSERT INTO PERSON VALUES (1,'Dave','Wolf', 62);
INSERT INTO PERSON VALUES (2,'Peg','Blaine', 60);
INSERT INTO PERSON VALUES (3,'Bart','Simpson', 10);
INSERT INTO PERSON VALUES (4,'Crazy Cat Laby','', 99);

SELECT * FROM PERSON;

CREATE TABLE PET (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PET_NAME VARCHAR(255),
    BREED VARCHAR(255),
    AGE INTEGER,
    DEAD INTEGER,
    PRIMARY KEY (ID)
);

SELECT * FROM PET;

INSERT INTO PET VALUES (NULL, 'Fifi','dog', 4,1);
INSERT INTO PET VALUES (NULL, 'Toto','dog', 8,1);
INSERT INTO PET VALUES (NULL, 'Cat1','cat', 5,1);
INSERT INTO PET VALUES (NULL, 'Cat2','cat', 5,1);
INSERT INTO PET VALUES (NULL, 'Cat3','cat', 6,1);
INSERT INTO PET VALUES (NULL, 'Cat4','cat', 8,1);
INSERT INTO PET VALUES (NULL, 'Cat5','cat', 3,1);


CREATE TABLE PERSON_PET (
    PERSON_ID INTEGER NOT NULL REFERENCES PERSON(ID),
    PET_ID INTEGER NOT NULL REFERENCES PET(ID)
);


INSERT INTO PERSON_PET VALUES (1, 1);
INSERT INTO PERSON_PET VALUES (2, 2);
INSERT INTO PERSON_PET VALUES (2, 1);
INSERT INTO PERSON_PET VALUES (3, 3);
INSERT INTO PERSON_PET VALUES (3, 4);
INSERT INTO PERSON_PET VALUES (3, 5);
INSERT INTO PERSON_PET VALUES (3, 6);
INSERT INTO PERSON_PET VALUES (3, 7);

SELECT * FROM PERSON_PET;